version: "3"


services:

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    container_name: postgres
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=$(DB_USER)
      - POSTGRES_PASSWORD=$(DB_PASSWORD)
      - POSTGRES_DB=$(DB_PORT)
#      - DATABASE_HOST=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  forest_app:
    build:
      context: .

    ports:
      - "9000:9000"
    depends_on:
      - postgres

