// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"awesomeProject/api"
	"awesomeProject/api/handler"
	"awesomeProject/config"
	"awesomeProject/db"
	"awesomeProject/repository"
	"awesomeProject/usecase"
	"awesomeProject/utils/logger"
)

// Injectors from wire.go:

func InitServer() (*api.HttpServer, error) {
	configConfig := config.GetConfig()
	sqlDB, err := db.ConnectDb(configConfig)
	if err != nil {
		return nil, err
	}
	forestRepository := repository.NewForestRepo(sqlDB)
	forestService := usecase.NewForestService(forestRepository)
	slogLogger := logger.NewLogger()
	forestHandler := handler.NewForestHandler(forestService, slogLogger)
	addrString := api.ProvideAddrString(configConfig)
	httpServer := api.NewHttpServer(forestHandler, addrString)
	return httpServer, nil
}

// wire.go:

func Co() *config.Config {
	return &config.Config{}
}
